apiVersion: v1
kind: Service
metadata:
  name: fastapi-production-service
spec:
  type: NodePort
  selector:
    app: fastapi-production
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30001